# Generated by Django 5.0.3 on 2024-04-24 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resenha',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='resenha',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
