# Generated by Django 5.0.4 on 2024-04-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_resenha_data_criacao_livro_capa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenha',
            name='nota',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
